### ISSUE TITLE
w4 2.a) Add Automatic Deployment of your CSV Database Web Service

### ISSUE THREAD

**Issue by jfho** [ITU-BDSA23-GROUP14/Chirp#38]
### 2.a) Add Automatic Deployment of your CSV Database Web Service

Add automatic deployments of your refactored CSV database to Azure App Services as a GitHub Action.
Likely the easiest way to configure a respective GitHub Actions workflow, is by registering the web service once on Azure App Services in the following way:
An illustrated guide of the following steps is accessible [here](https://app.tango.us/app/workflow/Creating-a-Remote-Azure-Database-for--NET-7--STS--on-Linux-with-Deployment-Center-cd9c4e3977184b7fb2a7e2d239e4d54f):

* Log onto <https://portal.azure.com/#home>
* Click the following sequence: top tab `App Services` → `+ Create` → choose `Web App`
* Set `Name` to `bdsagroup<no>chirpremotedb`, where `<no>` has to be replaced with the number of your group.
* Set `Region` to `North Europe`
* Set `Runtime stack` to `.NET 7 (STS)`
* Choose `Operating system` `Linux`
* Choose `Pricing Plan` `Free F1 (Shared infrastructure)`
* In the bottom, click the button `Review + create`
* After checking that all configuration is as expected, click the button `Create` in the bottom

* After reading a message saying _"`Your deployment is complete`"_, click `Go to resource`
* On the left choose `Deployment Center`
* Under `Source`, select `GitHub`
* Click `Authorize`
* Now choose organization (for you, it is your GitHub organization, i.e., `ITU-BDSA23-GROUP<no>`), your repository (`Chirp`) and the `main` branch
* Finish by clicking the `Save` button on the top

The last steps automatically create and store a GitHub Actions workflow in your repository and it automatically configures the required environment variables and secrets on GitHub.

In case your project is organized into `src` and `test` directories, you have to point the build and publish commands to the right projects in the repository:
  - Change lines 25 - 29 to:
  ```yaml
      - name: Build with dotnet
        run: dotnet build src/<Your.Chirp.CSVDB.Service>/ --configuration Release

      - name: dotnet publish
        run: dotnet publish src/<Your.Chirp.CSVDB.Service>/ -c Release -o ${{env.DOTNET_ROOT}}/myapp
  ```

After successful execution of the workflow, the app is available under: `https://bdsagroup<no>chirpremotedb.azurewebsites.net/`

### User Story
As a user, I want to always have the latest version of Chirp available

### Acceptance Criteria
* Created Azure Web App
* Created GitHub actions workflow for autodeployment
